#!/usr/bin/env ruby

require_relative '../lib/robot'
robot = Robot.new
while true do
  begin
    robot.process_command(gets)
  rescue Robot::InvalidCommandError
    puts 'Invalid command. Try again.'
  end
end